#!/bin/bash
#Scripting file for running multiple training instances with (DR)MSD. If there are more CUDA cores on your machine the device IDs can be changed.
#General usage: CUDA_VISIBLE_DEVICES=<CUDA DEVICE ID> timeout <days>d python X-rayDRMSDManyMaterialsTrue_train_segm.py <Dataset> <GroundTruth> <Datareduction> (leave Datareduction 0 for no reduction)
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py Data GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py Data GT [2]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample2_PCAData_2compData GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample5_NMFData_2compData GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_LDAData_1compDataGT GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT [1]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT [2]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT [10]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT [60]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py DataNoise GT [200]
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample2_PCAData_1compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample2_PCAData_2compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample2_PCAData_10compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample2_PCAData_60compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample3_PCAData_200compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample5_NMFData_1compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample5_NMFData_2compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample5_NMFData_10compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample5_NMFData_60compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_NMFData_200compDataNoise GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_LDAData_1compDataNoiseGT GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_LDAData_2compDataNoiseGT GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_LDAData_10compDataNoiseGT GT 0
CUDA_VISIBLE_DEVICES=0 timeout 20s python X-rayDRMSDManyMaterialsTrue_train_segm.py FULLTrainingSet_Sample6_LDAData_60compDataNoiseGT GT 0
